export const skillsSet = [
	{ id: 1, skill: 'JavaScript' },
	{ id: 2, skill: 'TypeScript' },
	{ id: 3, skill: 'React.js' },
	{ id: 4, skill: 'Next.js' },
	{ id: 5, skill: 'SCSS' },
	{ id: 6, skill: 'Python' },
	{ id: 7, skill: 'Django' },
	{ id: 8, skill: 'Tailwind CSS' },
	{ id: 9, skill: 'MongoDB' },
	{ id: 10, skill: 'PostgreSQL' },
	{ id: 11, skill: 'Node.js' },
	{ id: 12, skill: 'Express.js' },
	{ id: 13, skill: 'Spring Boot' },
	{ id: 14, skill: 'GraphQL' },
	{ id: 15, skill: 'Apollo' },
	{ id: 16, skill: 'Redux' },
	{ id: 17, skill: 'Framer Motion' },
	{ id: 18, skill: 'Webpack' },
	{ id: 19, skill: 'Vite' },
	{ id: 20, skill: 'Docker' },
	{ id: 21, skill: 'AWS' },
	{ id: 22, skill: 'Firebase' },
	{ id: 23, skill: 'Git' },
	{ id: 24, skill: 'GitHub' },
	{ id: 25, skill: 'Figma' },
	{ id: 26, skill: 'Pandas' },
	{ id: 27, skill: 'Jupyter' },
];
